apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::502973571985:role/eksctl-simple-jwt-api-nodegroup-ng-NodeInstanceRole-1XcmVGspAIzR
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::502973571985:role/UdacityFlaskDeployCBKubectlRole
      username: build  
kind: ConfigMap
metadata:
  creationTimestamp: "2024-01-23T15:57:33Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1407"
  uid: bdf088a2-1e6b-4fd4-b706-f0bc0e52bc07